DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS quests;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS sessions;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE quests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  diet TEXT NOT NULL,
  participating BOOL NOT NULL,
  responded TIMESTAMP DEFAULT 0,
  edited TIMESTAMP DEFAULT 0,

  grp_id INT NOT NULL,
  type_id INT NOT NULL,

  FOREIGN KEY (grp_id) REFERENCES groups (id),
  FOREIGN KEY (type_id) REFERENCES types (id)
);

CREATE TABLE groups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  passkey TEXT NOT NULL
);

CREATE TABLE types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,

  FOREIGN KEY (user_id) REFERENCES users (id)
);
